name=SerialMP3
version=1.2.0
author=Spinney20
maintainer=Spinney20
sentence=A library for Serial MP3 Player board GD3300D/TD5580A chip (Modified and Improved).
paragraph=An improved and optimized library to control the Serial MP3 Player module GD3300D/TD5580A, featuring enhanced stability and additional functionalities.
category=Audio
url=https://github.com/Spinney20/
architectures=*
includes=SerialMP3.h
